---
- name: "[{{ name }}] Конфигурация секрета"
  include: "../secret.yml"
  loop:
    - rabbitmq-env.conf
  loop_control:
    loop_var: secret_item

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ version }}"
        state: present
        networks:
          - name: "{{ docker_overlay_network_name }}"
        secrets:
          - secret_name: rabbitmq-env.conf
            filename: /etc/rabbitmq/rabbitmq-env.conf
        env:
          - "AMQP_HOSTNAME={{ name }}"
          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        placement:
          constraints:
            - node.hostname == server4
        healthcheck:
          test: [ "CMD", "rabbitmqctl", "status" ]
          start_period: 3s
          interval: 30s
          timeout: 3s
          retries: 30
  tags: "{{ name }}"