---
- name: "[{{ name }}] Выкладка конфига"
  include: "../config.yml"
  loop:
    - rabbitmq.conf
    - rabbitmq-definitions.json
  loop_control:
    loop_var: config_item

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ version }}"
        state: present
        networks:
          - name: "{{ docker_overlay_network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 15673
            target_port: 15672
        configs:
          - config_name: rabbitmq.conf
            filename: /etc/rabbitmq/rabbitmq.conf
          - config_name: rabbitmq-definitions.json
            filename: /etc/rabbitmq/rabbitmq-definitions.json
        env:
          - "AMQP_HOSTNAME={{ name }}"
        placement:
          constraints:
            - node.hostname == server4
        healthcheck:
          test: [ "CMD", "rabbitmqctl", "status" ]
          start_period: 3s
          interval: 30s
          timeout: 3s
          retries: 30
  tags: "{{ name }}"