---
- name: "[{{ name }}] Конфигурация секрета"
  include: "../secret.yml"
  loop:
    - .env
  loop_control:
    loop_var: secret_item

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ version }}"
        state: present
        networks:
          - name: "{{ docker_overlay_network_name }}"
        secrets:
          - secret_name: user
            filename: "/run/secrets/secret.txt"
        env_files:
          - .env
        env:
          - AMQP_HOSTNAME=rmq
          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  tags: "{{ name }}"