---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ version }}"
        state: present
        networks:
          - name: "{{ docker_overlay_network_name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
          - AMQP_EXCHANGE=xchg_integrations
          - AMQP_HOSTNAME=rmq
          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  tags: "{{ name }}"