galaxy_info:
  role_name: mysql_copy_init_script
  description: Копирование стартового SQL-скрипта
  author: Andrey Polnikov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all