app:
  cors:
    allowedOrigins: http://localhost:3000
  jwtCookieName: mcfly
  # node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"
  jwtSecret: 21107542ca08149e06e5cedf515e56d60cf7e64348abfcc32e6407b75f672aa4384c6ffaf9fce1801bc61f506a232c5921ec4705e69fd76f8aeeb0427d76a4ed
  jwtExpirationInMs: 604800000

logging:
  level:
    ROOT: info
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.orm.jpa: debug
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.transaction: debug


server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sb3_react?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: sb3_react_user
    password: password
  flyway:
    user: sb3_react_admin
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  mvc:
    log-request-details: true
  profiles:
    default: dev
  rabbitmq:
    host: localhost
    username: admin
    password: gjkybrjd
    port: 5672
    virtual-host: /
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/sb3_react?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  rabbitmq:
    host: rmq
app:
  cors:
    allowedOrigins: http://localhost:8081