version: '3.8'
services:
  sb3-backend:
    image: sb3_backend:latest
    build:
      context: ./services/backend
      dockerfile: production.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sb3_react?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 3
  react-frontend:
    image: react_frontend:latest
    build:
      context: ./services/frontend
      dockerfile: production.Dockerfile
    restart: always
    ports:
      - '8081:80'
    volumes:
      - /app/node_modules
      - ./.react_frontend:/app
    depends_on:
      sb3-backend:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:80
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 3
  mailer:
    image: mailer:latest
    build:
      context: ./services/mailer
      dockerfile: production.Dockerfile
    restart: always
    depends_on:
      rmq:
        condition: service_healthy
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gjkybrjd
      - MYSQL_DATABASE=sb3_react
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./services/backend/src/main/resources/db/script/mysql-setup.sql:/docker-entrypoint-initdb.d/mysql-setup.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 3
  rmq:
    image: rabbitmq:3.12.2-management
    restart: always
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json:ro
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db:
    driver: local