app:
  rabbitmq:
    queues:
      emailConfirmQueue:
        name: email-confirmation

spring:
  mail:
    username: sbreact438@gmail.com
    password: gjkybrjd
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  profiles:
    default: dev
  rabbitmq:
    host: localhost
    username: admin
    password: gjkybrjd
    port: 5672
    virtual-host: /
---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rmq