---
- name: "[MySQL Выкладка сервиса"
  block:
    - name: "[MySQL] Выкладываем стартовый скрипт"
      ansible.builtin.copy:
        src: ../../services/backend/src/main/resources/db/script/mysql-setup.sql
        dest: /etc/mysql-setup.sql
    - name: "[MySQL] Выкладываем сервис"
      docker_container:
        name: mysql
        image: mysql:{{ version }}
        volumes:
          - db:/var/lib/mysql
          - /etc/mysql-setup.sql:/docker-entrypoint-initdb.d/mysql-setup.sql
        restart: true
        networks:
          - name: "{{ docker_overlay_network_name }}"
        env:
          MYSQL_ROOT_PASSWORD: gjkybrjd
          MYSQL_DATABASE: sb3_react
  #          MYSQL_USER: wordpress
  #          MYSQL_PASSWORD: wordpress
  tags: "mysql"