---
docker_local_registry_name: "localhost:5000/"

docker_swarm_advertise_addr: 10.11.10.2

docker_overlay_network_name: docker-overlay-network

services:
  - name: mysql
    version: 8.0.33
    build: false
  - name: rmq
    version: 3.12.2-management
    build: false
  - name: backend
    version: latest
    build: true
  - name: mailer
    version: latest
    build: true
  - name: frontend
    version: latest
    build: true
  - name: nginx
    version: latest
    build: false

rmq_defaults:
  - name: AMQP_EXCHANGE
    value: xchg_integrations
  - name: AMQP_HOSTNAME
    value: rmq