---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Ждём MySQL"
      wait_for:
        host: localhost
        port: 3306
        connect_timeout: 3
        delay: 3
        timeout: 100

    - name: "[{{ name }}] Ждём RabbitMQ"
      wait_for:
        host: localhost
        port: 15673
        connect_timeout: 3
        delay: 3
        timeout: 100

    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        hostname: "{{ name }}"
        image: "{{ docker_local_registry_name }}{{ name }}:{{ version }}"
        state: present
        force_update: true
        networks:
          - name: "{{ docker_overlay_network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 8082
            target_port: 8080
        placement:
          constraints:
            - node.hostname == server1
        healthcheck:
          test: wget --no-verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
          start_period: 3s
          interval: 30s
          timeout: 3s
          retries: 30
  tags: "{{ name }}"