---
- name: "[{{ name }}] Конфигурация секрета"
  include: "../secret.yml"
  loop:
    - db_root_password
  loop_control:
    loop_var: secret_item

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "mysql:{{ version }}"
        state: present
        networks:
          - "{{ docker_overlay_network_name }}"
        mounts:
          - source: db
            target: /var/lib/mysql
            type: volume
          - source: /tmp/mysql-setup.sql
            target: /docker-entrypoint-initdb.d/mysql-setup.sql
            type: bind
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3306
            target_port: 3306
        secrets:
          - secret_name: db_root_password
            filename: /run/secrets/db_root_password
        env:
          MYSQL_DATABASE: sb3_react
          MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        placement:
          constraints:
            - node.hostname == server5
  tags: "{{ name }}"