---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "mysql:{{ version }}"
        state: present
        networks:
          - "{{ docker_overlay_network_name }}"
        mounts:
          - source: db
            target: /var/lib/mysql
            type: volume
          - source: /tmp/mysql-setup.sql
            target: /docker-entrypoint-initdb.d/mysql-setup.sql
            type: bind
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3306
            target_port: 3306
        env:
          MYSQL_ROOT_PASSWORD: gjkybrjd
          MYSQL_DATABASE: sb3_react
        placement:
          constraints:
            - node.hostname == server5
  tags: "{{ name }}"