---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем стартовый скрипт"
      ansible.builtin.copy:
        src: ../../services/backend/src/main/resources/db/script/mysql-setup.sql
        dest: /tmp/mysql-setup.sql
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "mysql:{{ version }}"
        state: present
        networks:
          - "{{ docker_overlay_network_name }}"
        volumes:
          - db:/var/lib/mysql
          - /tmp/mysql-setup.sql:/docker-entrypoint-initdb.d/mysql-setup.sql
        published_ports: "3306:3306"
        exposed_ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: gjkybrjd
          MYSQL_DATABASE: sb3_react
        placement:
          constraints:
            - node.hostname == mysql
  tags: "{{ name }}"