---
- name: "[{{ name }}] Ждём backend"
  wait_for:
    host: localhost
    port: 8082
    connect_timeout: 3
    delay: 3
    timeout: 100

- name: "[{{ name }}] Конфигурация конфига"
  include: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item

- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервиса"
      community.docker.docker_swarm_service:
        debug: true
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        networks:
          - name: "{{ docker_overlay_network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
          - mode: ingress
            protocol: tcp
            published_port: 8080
            target_port: 8080
          - mode: ingress
            protocol: tcp
            published_port: 15672
            target_port: 15672
        configs:
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf"
        healthcheck:
          test: [ "CMD", "curl", "--fail", "localhost/nginx-health" ]
          start_period: 30s
          interval: 30s
          timeout: 3s
          retries: 30
  tags: "{{ name }}"