app:
  cors:
    allowedOrigins: http://localhost:3000
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

logging:
  level:
    ROOT: INFO
    org.springframework.orm.jpa: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.springframework.transaction: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: polling_user
    password: password
  flyway:
    user: polling_admin
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true