app:
  cors:
    allowedOrigins: http://localhost:3000
  jwtCookieName: mcfly
  # node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"
  jwtSecret: 21107542ca08149e06e5cedf515e56d60cf7e64348abfcc32e6407b75f672aa4384c6ffaf9fce1801bc61f506a232c5921ec4705e69fd76f8aeeb0427d76a4ed
  jwtExpirationInMs: 604800000

logging:
  level:
    ROOT: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.transaction: DEBUG


server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sb3_react?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: sb3_react_user
    password: password
  flyway:
    user: sb3_react_admin
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  mvc:
    log-request-details: true