---
- name: "{{ name }}: Создаем секрет"
  vars:
    secret_file: "{{ lookup('template', '{{ name }}/{{ secret_item }}.j2') }}"
  community.docker.docker_secret:
    name: "{{ secret_item }}"
    data: "{{ secret_file | b64encode }}"
    labels:
      secret: "{{ secret_file | hash('sha1') }}"
    data_is_b64: true
    state: present