galaxy_info:
  role_name: deploy_mysql
  description: Выкладка MySQL сервиса
  author: Andrey Polnikov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all